language: node_js
# cache:
#   directories:
#     - dist

node_js:
- '6.9.4'

install:
- npm install

script:
- npm run build

# deploy:
# - provider: npm
#   email: onpm@microsoft.com
#   skip_cleanup: true
#   api_key:
#     secure:
#   on:
#     branch: master
#     tags: true